# encrypts generated pcap har files
version: "3"
services:
  encrypt:
    image: lblod/encryption-service
    links:
      - database:database
    volumes:
      - pcaps:/data/pcaps
      - processed_hars:/data/hars
      - ./keys:/app/keys
    environment:
      ENCRYPT_RECIPIENT: 'info@redpencil.io'
      ENCRYPT_AFTER_MINUTES: 60
      ENCRYPT_GLOB: '/data/pcaps/*.{pcap,har} /data/hars/*.har'
