version: '3.4'

services:
  monitor:
    image: redpencil/docker-monitor-service
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MONITOR_SYNC_INTERVAL: 2500
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  capture:
    image: redpencil/docker-network-capture-service
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CAPTURE_CONTAINER_FILTER: '?uri docker:label ?theLabel. ?theLabel docker:key "logging"'
      CAPTURE_SYNC_INTERVAL: 2500
      MONITOR_IMAGE: "test-packetbeat"
    depends_on: # Ensures this service is stopped before the database stops.
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.8.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
