version: '3.6'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  logstash:
    volumes:
      - ./config/logstash/pipelines/http-encrypt-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - logs:/usr/share/logstash/data:rw
    environment:
      LOGFILE_FORMAT_STRING: '/usr/share/logstash/data/audit/http-log-%{+YYYY-MM-dd-HH}.json'
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    logging: *default-logging
  encrypt:
    image: redpencil/file-encryption-service:1.1.0
    volumes:
      - logs:/data/logs:rw
      - ./encrypted:/data/encrypted:rw
      - ./keys:/keys:ro
    environment:
      ENCRYPT_RECIPIENT: 'info@redpencil.io'
      ENCRYPT_AFTER_MINUTES: 60
      ENCRYPT_GLOB: '/data/logs/audit/http-log-*.json'
      ENCRYPTED_DIR: '/data/encrypted'
      #ENCRYPT_INTERVAL: 3600 # default value
    logging: *default-logging

volumes:
  logs:
