version: '3.4'

services:
  database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data:rw
      - ./data/db/virtuoso.ini:/data/virtuoso.ini
