# load hars into an elk stack
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - "discovery.type=single-node"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  har-to-elastic:
    image: lblod/har-to-elastic-service
    environment:
      ELASTIC_HOST: elasticsearch
      HAR_FOLDER: '/data/hars/*'
    volumes:
      - hars:/data/hars
      - processed_hars:/data/processed
    links:
      - "elasticsearch:elasticsearch"
volumes:
  esdata:
  processed_hars:
  hars:
