# NOTE: this is the production Docker Compose configuration file. DO NOT put
#       any stuff that must be available only in development. Please use the
#       file docker-compose.override.yml instead.
version: "2"
services:
  swarm-logger:
    build: ./mu-swarm-logger-service
    links:
      - database:database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /src/run.py --debug sparql
  database:
    image: tenforce/virtuoso:1.1.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
  event-query:
    build: ./mu-docker-event-query
    links:
      - database:database
    volumes:
      - ./containers:/usrc/src/app/containers/
      - ./mu-docker-event-query/src:/app
    environment:
      MODE: 'development'
      SLEEP_PERIOD: '10'
