# NOTE: this docker-compose.yml needs to be completed by either the
#       docker-compose.visualize.yml and/or docker-compose.encrypt.yml
#       if you have not removed the .env file docker-compose.visualize will be included by default

version: "3"
services:
  monitor:
    image: lblod/docker-monitor-service
    links:
      - database:database
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  database:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db/:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  pcap:
    image: lblod/docker-network-capture-service
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pcaps:/data
    environment:
      CAPTURE_CONTAINER_FILTER: '?uri docker:label ?theLabel. ?theLabel docker:key "logging"'
      # PCAP_VOLUME: /your/absolute/path
      PCAP_VOLUME: pcaps
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  pcap-to-har:
    image: lblod/mu-har-transformation-service:0.1.0
    volumes:
      - pcaps:/data/pcaps
      - hars:/data/hars
      - processed_pcaps:/data/processed
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  pcaps:
    external: true
  hars:
  processed_pcaps:
