version: '3.6'

services:
  monitor:
    image: redpencil/docker-monitor-service
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MONITOR_SYNC_INTERVAL: 5000
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  capture:
    image: redpencil/docker-network-capture-service
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CAPTURE_CONTAINER_FILTER: '?uri docker:label/docker:key "logging".'
      CAPTURE_SYNC_INTERVAL: 60000
      MONITOR_IMAGE: "redpencil/http-logger-packetbeat-service"
      LOGSTASH_NETWORK: "logstash-network"
    depends_on: # Ensures this service is stopped before the db stops, because we need the db to clean up.
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.8.1
    user: "root"
    networks:
      - default
      - logstash-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  logstash-network:
    name: "logstash-network" # Explicitly set the name to prevent scoping w/ the compose project name
