version: '3.6'

services:
  monitor:
    image: redpencil/docker-monitor-service
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      MONITOR_SYNC_INTERVAL: 5000
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  capture:
    image: redpencil/docker-network-capture-service
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CAPTURE_CONTAINER_FILTER: '?uri docker:label/docker:key "logging".'
      CAPTURE_SYNC_INTERVAL: 60000
      MONITOR_IMAGE: "redpencil/http-logger-packetbeat-service"
      LOGSTASH_NETWORK: "logstash-network"
      # Default configuration values for packetbeat
      PACKETBEAT_MAX_MESSAGE_SIZE: 102400 # Maximum total message size in bytes
      PACKETBEAT_LISTEN_PORTS: "[80, 81, 88, 8080, 8890, 1111, 4200, 9229]" # YAML array of ports
    depends_on: # Ensures this service is stopped before the db stops, because we need the db to clean up.
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    image: redpencil/http-logger-logstash-service
    user: "root"
    networks:
      - default
      - logstash-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data:rw
      - ./data/db/virtuoso.ini:/data/virtuoso.ini:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  database:
    image: semtech/mu-authorization
    depends_on:
      - triplestore
      - delta
    volumes:
      - ./config/authorization:/config:ro
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      DATABASE_COMPATIBILITY: "Virtuoso"
      # Debug logging
#      LOG_SERVER_CONFIGURATION: "true"
#      INSPECT_OUTGOING_SPARQL_QUERIES: "true"
#      LOG_OUTGOING_SPARQL_QUERIES: "true"
#      INSPECT_INCOMING_SPARQL_QUERIES: "true"
#      LOG_INCOMING_SPARQL_QUERIES: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  delta:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config:ro

networks:
  logstash-network:
    name: "logstash-network" # Explicitly set the name to prevent scoping w/ the compose project name
    driver: "bridge"
