# NOTE: this is the production Docker Compose configuration file. DO NOT put
#       any stuff that must be available only in development. Please use the
#       file docker-compose.override.yml instead.
version: "3"
services:
  monitor:
    image: lblod/docker-monitor-service
    links:
      - database:database
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db/:/data
  pcap:
    image: lblod/docker-network-capture-service
    privileged: true
    userns_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CAPTURE_CONTAINER_FILTER: '?uri docker:label ?theLabel. ?theLabel docker:key "logging"'
      # PCAP_VOLUME: /your/absolute/path
      PCAP_VOLUME: pcaps
volumes:
  pcaps
